CREATE SEQUENCE TEST
    MAXVALUE 9999
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

DROP SEQUENCE TEST;    
SELECT SYSDATE FROM dual;
SELECT TEST.NextVal, TEST.currval FROM DUAL;

CREATE SEQUENCE TEST2
    MAXVALUE 10000
    START WITH 10
    INCREMENT BY 10
    CYCLE
    NOCACHE;

CREATE SEQUENCE TEST3
    MAXVALUE 100
    START WITH 10
    INCREMENT BY 10
    CYCLE
    NOCACHE;
    
SELECT * FROM sys.user_sequences;
SELECT * FROM sys.user_tables;
SELECT * FROM sys.all_sequences;
SELECT * FROM sys.all_tables;
SELECT * FROM sys.dba_sequences;
SELECT * FROM sys.dba_tables;
SELECT TEST2.NextVal, TEST2.currval FROM DUAL;
SELECT TEST3.NextVal FROM DUAL;

CREATE TABLE aluno(
    ra NUMBER NOT NULL,
    nome VARCHAR(80) NOT NULL,
    CONSTRAINT PK_aluno PRIMARY KEY(ra)
);

INSERT INTO aluno(ra, nome) VALUES(TEST.nextval, 'JILERTO');
INSERT INTO aluno(ra, nome) VALUES(TEST.nextval, 'ROLAUDO');
SELECT * FROM aluno;

CREATE SEQUENCE TEST4
    MINVALUE 1
    MAXVALUE 9000
    START WITH 500
    INCREMENT BY -1
    CYCLE 
    NOCACHE;
    
SELECT TEST4.nextval FROM DUAL;
SELECT COUNT(*) FROM dba_tables;